### ISSUE TITLE
модуль берет оплату на 25% выше реальной стоимости товара.

### ISSUE THREAD

**Issue by oleg-rom** [cloudipsp/opencart-all-versions#11]
Похоже с плагином Fondy для opencart проблемы, т.к., когда я выставляю оплату в рублях (для удобства клиента), то при переходе к оплате цена увеличивается почти на 25% (еще до того, как клиент введет банковские данные - т.е. вопрос не в конвертации). Я сам создал такой платеж и проверил. Похоже, что проблема именно при оплате в рублях.

**Comment by has-well** [comment]
Добрый день, модуль никак не корректирует сумму оплаты, данные подтягиваются из заказа, возможно у Вас установленны сторонние плагины которые влияют на сумму заказа
