### ISSUE TITLE
Как заменить номер заказа на товар в карточке оплаты?

### ISSUE THREAD

**Issue by Balam4ik** [cloudipsp/opencart-all-versions#12]
Здравствуйте!

Подскажите, как заменить значение в карточке оплаты, чтобы туда попадал не номер заказа, а хотя бы первый товар с корзины?

С 1 февраля по законодательству РФ все предприниматели должны указывать наименование товара в чеке. А сейчас в чек попадает номер заказа и это нарушение.

На скриншоте вместо номера заказа, должен попадать товар или услуга! Как сделать, чтобы хотя бы 1 товар с корзины сюда попадал? Пожалуйста, подскажите! http://prntscr.com/10cbp31

В ОФД приходит именно номер заказа, а должен приходить хоть какое-то наименование товара. Данный модуль не советует по умолчанию законодательству РФ и клиенту нужно самому допилить его. Может быть можете это сделать?

**Comment by has-well** [comment]
Здравствуйте!
Для opencart 3й версии есть обновленный модуль в котором передаются названия товаров, https://github.com/cloudipsp/opencart-v3/releases

**Comment by Balam4ik** [comment]
А для версий 2.0-2.2? Это более распространённая версия opencart

**Comment by has-well** [comment]
К сожалению версии 2.* являются устаревшими, Вы можете подать запрос на добработку связавшись с технической поддержкой через онлайн чат на сайте

**Comment by Balam4ik** [comment]
Понятно. Спасибо
